<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Fiserv\Payments\Block\Customer\Bluepay\VaultAchRenderer;
use Magento\Vault\Api\Data\PaymentTokenInterface;

/** @var VaultAchRenderer $block */

$summary = $block->getTokenSummary();
$confirmDeleteMessage = sprintf('%s: %s?', __('Are you sure you want to delete this stored payment account?'), $summary);

?>
<tr>
    <td data-th="<?= $block->escapeHtmlAttr(__('ACH Account')) ?>" class="col ach-account">
        <span><?= $block->escapeHtml($block->getAchAccountString()) ?></span>
    </td>

    <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
        <form
            class="form"
            action="<?= $block->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>"
            method="post">
            <?= $block->getBlockHtml('formkey') ?>
            <input
                name="<?= /* @noEscape */ PaymentTokenInterface::PUBLIC_HASH ?>"
                value="<?= /* @noEscape */ $block->getToken()->getPublicHash() ?>"
                type="hidden"/>
            <button type="submit"
                    class="action delete"
                    data-mage-init='{
                        "Magento_Vault/js/customer_account/deleteWidget":{
                            "type": "popup",
                            "modalClass": "my-credit-cards-popup",
                            "toggleEvent": "click",
                            "title": "<?= $block->escapeHtml(__('Delete')) ?>",
                            "content":"<?= $block->escapeHtml($confirmDeleteMessage) ?>"
                        }
                    }'>
                <span><?= $block->escapeHtml(__('Delete')) ?></span>
            </button>
        </form>
    </td>
</tr>
